# Project information
site_name: Project Euler solutions
site_description: Solutions to the first 100 problems of [Project Euler](https://projecteuler.net/).
site_author: Sudip Sinha
site_url: https://SudipSinha.github.io/Project-Euler

# Source repository
repo_name: SudipSinha/Project-Euler
repo_url: https://github.com/SudipSinha/Project-Euler

# Copyright
copyright: <a href="http://github.com/SudipSinha">Sudip Sinha</a> &copy; 2020 onwards

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  # markdown_katex only works for GitLab syntax ($` n `$ and ```math n ```)
  # - markdown_katex:
  #     no_inline_svg: True
  #     insert_fonts_css: True
  #     macro-file: macros.tex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true

# Configuration
theme:
  name: material
  language: en
  features:
    - instant
    - tabs
  # favicon: assets/favicon.png
  # palette:
  #   primary: teal
  #   accent: cyan
  icon:
    logo: fontawesome/solid/infinity
    repo: fontawesome/brands/github

extra_javascript:
  # For KaTeX, use the following three lines.
  - js/arithmatex2katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js
  # For MathJax, use the following two lines.
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# For KaTeX, we need to use the CSS files too.
extra_css:
  - css/katex.my.css
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css

# Social
# Find icon folders [here](https://github.com/squidfunk/mkdocs-material/tree/master/material/.icons/)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SudipSinha
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sudipsinha
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SudipSinha
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SudipSinha
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0001-5188-1336
    - icon: fontawesome/regular/envelope
      link: mailto:SudipSinha.Bappa@Gmail.com


# nav:
#   - Preface: index.md
#   - I Foundations:
#       - 1 The Role of Algorithms in Computing:
#           - 1.1 Algorithms: Chap01/1.1.md
#           - 1.2 Algorithms as a technology: Chap01/1.2.md
#           - Chap 1 Problems:
#               - Problem 1-1: Chap01/Problems/1-1.md
#       - 2 Getting Started:
#           - 2.1 Insertion sort: Chap02/2.1.md
#           - 2.2 Analyzing algorithms: Chap02/2.2.md
#           - 2.3 Designing algorithms: Chap02/2.3.md
#           - Chap 2 Problems:
#               - 2-1 Insertion sort on small arrays in merge sort: Chap02/Problems/2-1.md
#               - 2-2 Correctness of bubblesort: Chap02/Problems/2-2.md
#               - 2-3 Correctness of Horner's rule: Chap02/Problems/2-3.md
#               - 2-4 Inversions: Chap02/Problems/2-4.md